#!/usr/bin/env groovy

pipeline {
    agent any

    stages {
        stage('test'){
            steps {
                script {
                    def branches = [:]
                    for (int i = 0; i < 4; i++){
                        def index = i
                        branches["test${i}"] = {
                            build   propagate: false,
                                    job: 'test',
                                    parameters: [string(name: 'dummy', value: "${index}")]
                        }
                    }
                    parallel branches
                }
            }
        }
    }
}
